// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awdbgohpikkdifasdggb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3ZGJnb2hwaWtrZGlmYXNkZ2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTg2NjEsImV4cCI6MjA2NTIzNDY2MX0.oQvqkNMhIoZrYVD4w8tSC7EkSnMm8ZplkyEuSjNdGrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);